apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: todoapp
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web 
        image: janakiramm/todo-app
        ports:
        - containerPort: 3000
